// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClXVIz_l0hVo8f4vkp9uudlUDSmROBJdU',
    appId: '1:515675750183:web:32a4d63067def495303302',
    messagingSenderId: '515675750183',
    projectId: 'chat-app-5f987',
    authDomain: 'chat-app-5f987.firebaseapp.com',
    storageBucket: 'chat-app-5f987.firebasestorage.app',
    measurementId: 'G-VVYW05WH79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi-eXmiTh4a8sCNK3BqOUbtTFQLovCgXc',
    appId: '1:515675750183:android:06ffca469ff941c4303302',
    messagingSenderId: '515675750183',
    projectId: 'chat-app-5f987',
    storageBucket: 'chat-app-5f987.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl8Ut9Y9_VzP9KtwpB0dMKGBnkdoQHR5o',
    appId: '1:515675750183:ios:6fdb52e57f720ec3303302',
    messagingSenderId: '515675750183',
    projectId: 'chat-app-5f987',
    storageBucket: 'chat-app-5f987.firebasestorage.app',
    iosBundleId: 'com.example.chatboot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl8Ut9Y9_VzP9KtwpB0dMKGBnkdoQHR5o',
    appId: '1:515675750183:ios:6fdb52e57f720ec3303302',
    messagingSenderId: '515675750183',
    projectId: 'chat-app-5f987',
    storageBucket: 'chat-app-5f987.firebasestorage.app',
    iosBundleId: 'com.example.chatboot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClXVIz_l0hVo8f4vkp9uudlUDSmROBJdU',
    appId: '1:515675750183:web:086ac685cea95d49303302',
    messagingSenderId: '515675750183',
    projectId: 'chat-app-5f987',
    authDomain: 'chat-app-5f987.firebaseapp.com',
    storageBucket: 'chat-app-5f987.firebasestorage.app',
    measurementId: 'G-RRZW2KM63W',
  );
}
